# Generated by Django 2.2 on 2021-05-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_tokenimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenimage',
            name='image',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='webapp.Image', verbose_name='Token'),
        ),
    ]
